<?php
/** @var \Magento\Catalog\Block\Product\View $block */
$product = $block->getProduct();
if ($product && $product->getData('is_parking_ticket')): ?>
    <div id="parking-ticket-fields" data-bind="scope: 'parkingTicketForm'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        {
            "#parking-ticket-fields": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "parkingTicketForm": {
                            "component": "Epam_Parking/js/view/parking-fields",
                            "config": {
                                "isParkingTicket": <?= $block->escapeJs((bool) $product->getData('is_parking_ticket')) ? 'true' : 'false' ?>
                            }
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
